Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/09/2017
Var
numero: inteiro
Inicio
escreva ("numero par ou impar")
leia (numero)
caso numero
se numero mod 2=0 entao
escreva ("par")
senao
escreva ("impar")
fimse
Fimalgoritmo